services:

  Naehwelt\Shopware\ImportExport\Task:
    tags:
      - shopware.scheduled.task

  Naehwelt\Shopware\ImportExport\TaskHandler:
    arguments:
      - '@scheduled_task.repository'
      - '@monolog.logger'
    tags:
      - messenger.message_handler