#file: noinspection YAMLIncompatibleTypes
- name: sage_connect_product
  label: SageConnect-Profil Product
  source_entity: product
  config:
    createEntities: true
    updateEntities: true
    sage_connect:
      onBeforeImportRow:
      onBeforeImportRecord:
        DefaultProductVisibilities: []
        CalculateLinkedPrices: []

  update_by:
    - entityName: product
      mappedKey: productNumber
    - entityName: tax
      mappedKey: name
    - entityName: product_manufacturer
      mappedKey: translations.DEFAULT.name

  mapping:
    - key: productNumber
      mappedKey: product_number
    - key: translations.DEFAULT.name
      mappedKey: name
    - key: stock
      mappedKey: stock
    - key: price.DEFAULT.gross
      mappedKey: price_gross
    - key: manufacturer.translations.DEFAULT.name
      mappedKey: manufacturer_name
    - key: ean
      mappedKey: ean
    - key: manufacturerNumber
      mappedKey: manufacturer_number
    - key: cover.media.url
      mappedKey: cover_media_url
    - key: media
      mappedKey: media
    - key: visibilities.all
      mappedKey: sales_channel
    - key: price.DEFAULT.linked
      mappedKey: price_linked
      useDefaultValue: true
      defaultValue: 1
    - key: price.DEFAULT.net
      mappedKey: price_net
      useDefaultValue: true
      defaultValue: 0
    - key: tax.name
      mappedKey: tax_name
      useDefaultValue: true
      defaultValue: {{ config('core.tax.defaultTaxRate')|entity_tax.getName() }}
    - key: translations.DEFAULT.description
      mappedKey: description
    - key: active
      mappedKey: active
      useDefaultValue: true
      defaultValue: true
    - key: translations.DEFAULT.customSearchKeywords
      mappedKey: keywords
    - key: id
      mappedKey: id
